#!/bin/sh
wget    -P amicorpus/ES2002a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2002a/audio/ES2002a.Mix-Headset.wav
wget    -P amicorpus/ES2003a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2003a/audio/ES2003a.Mix-Headset.wav
wget    -P amicorpus/ES2004a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2004a/audio/ES2004a.Mix-Headset.wav
wget    -P amicorpus/ES2005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2005a/audio/ES2005a.Mix-Headset.wav
wget    -P amicorpus/ES2006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2006a/audio/ES2006a.Mix-Headset.wav
wget    -P amicorpus/ES2007a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2007a/audio/ES2007a.Mix-Headset.wav
wget    -P amicorpus/ES2008a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2008a/audio/ES2008a.Mix-Headset.wav
wget    -P amicorpus/ES2009a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2009a/audio/ES2009a.Mix-Headset.wav
wget    -P amicorpus/ES2010a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2010a/audio/ES2010a.Mix-Headset.wav
wget    -P amicorpus/ES2011a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2011a/audio/ES2011a.Mix-Headset.wav
wget    -P amicorpus/ES2012a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2012a/audio/ES2012a.Mix-Headset.wav
wget    -P amicorpus/ES2013a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2013a/audio/ES2013a.Mix-Headset.wav
wget    -P amicorpus/ES2014a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2014a/audio/ES2014a.Mix-Headset.wav
wget    -P amicorpus/ES2015a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2015a/audio/ES2015a.Mix-Headset.wav
wget    -P amicorpus/ES2016a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2016a/audio/ES2016a.Mix-Headset.wav
wget    -P amicorpus/IS1000a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1000a/audio/IS1000a.Mix-Headset.wav
wget    -P amicorpus/IS1001a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1001a/audio/IS1001a.Mix-Headset.wav
wget    -P amicorpus/IS1003a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1003a/audio/IS1003a.Mix-Headset.wav
wget    -P amicorpus/IS1004a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1004a/audio/IS1004a.Mix-Headset.wav
wget    -P amicorpus/IS1005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1005a/audio/IS1005a.Mix-Headset.wav
wget    -P amicorpus/IS1006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1006a/audio/IS1006a.Mix-Headset.wav
wget    -P amicorpus/IS1007a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1007a/audio/IS1007a.Mix-Headset.wav
wget    -P amicorpus/IS1008a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1008a/audio/IS1008a.Mix-Headset.wav
wget    -P amicorpus/IS1009a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1009a/audio/IS1009a.Mix-Headset.wav
wget    -P amicorpus/TS3003a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3003a/audio/TS3003a.Mix-Headset.wav
wget    -P amicorpus/TS3004a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3004a/audio/TS3004a.Mix-Headset.wav
wget    -P amicorpus/TS3005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005a/audio/TS3005a.Mix-Headset.wav
wget    -P amicorpus/TS3006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006a/audio/TS3006a.Mix-Headset.wav
wget    -P amicorpus/TS3007a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007a/audio/TS3007a.Mix-Headset.wav
wget    -P amicorpus/TS3008a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008a/audio/TS3008a.Mix-Headset.wav
wget    -P amicorpus/TS3009a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009a/audio/TS3009a.Mix-Headset.wav
wget    -P amicorpus/TS3010a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010a/audio/TS3010a.Mix-Headset.wav
wget    -P amicorpus/TS3011a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011a/audio/TS3011a.Mix-Headset.wav
wget    -P amicorpus/TS3012a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012a/audio/TS3012a.Mix-Headset.wav
wget    -P amicorpus/EN2001a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001a/audio/EN2001a.Mix-Headset.wav
wget    -P amicorpus/EN2001b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001b/audio/EN2001b.Mix-Headset.wav
wget    -P amicorpus/EN2001d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001d/audio/EN2001d.Mix-Headset.wav
wget    -P amicorpus/EN2001e/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001e/audio/EN2001e.Mix-Headset.wav
wget    -P amicorpus/EN2002a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002a/audio/EN2002a.Mix-Headset.wav
wget    -P amicorpus/EN2002b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002b/audio/EN2002b.Mix-Headset.wav
wget    -P amicorpus/EN2002c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002c/audio/EN2002c.Mix-Headset.wav
wget    -P amicorpus/EN2002d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002d/audio/EN2002d.Mix-Headset.wav
wget    -P amicorpus/EN2003a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2003a/audio/EN2003a.Mix-Headset.wav
wget    -P amicorpus/EN2004a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2004a/audio/EN2004a.Mix-Headset.wav
wget    -P amicorpus/EN2005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2005a/audio/EN2005a.Mix-Headset.wav
wget    -P amicorpus/EN2006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006a/audio/EN2006a.Mix-Headset.wav
wget    -P amicorpus/EN2006b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006b/audio/EN2006b.Mix-Headset.wav
wget    -P amicorpus/EN2009b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009b/audio/EN2009b.Mix-Headset.wav
wget    -P amicorpus/EN2009c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009c/audio/EN2009c.Mix-Headset.wav
wget    -P amicorpus/EN2009d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009d/audio/EN2009d.Mix-Headset.wav
wget    -P amicorpus/IB4001/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4001/audio/IB4001.Mix-Headset.wav
wget    -P amicorpus/IB4002/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4002/audio/IB4002.Mix-Headset.wav
wget    -P amicorpus/IB4003/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4003/audio/IB4003.Mix-Headset.wav
wget    -P amicorpus/IB4004/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4004/audio/IB4004.Mix-Headset.wav
wget    -P amicorpus/IB4005/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4005/audio/IB4005.Mix-Headset.wav
wget    -P amicorpus/IB4010/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4010/audio/IB4010.Mix-Headset.wav
wget    -P amicorpus/IB4011/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4011/audio/IB4011.Mix-Headset.wav
wget    -P amicorpus/IN1001/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1001/audio/IN1001.Mix-Headset.wav
wget    -P amicorpus/IN1002/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1002/audio/IN1002.Mix-Headset.wav
wget    -P amicorpus/IN1005/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1005/audio/IN1005.Mix-Headset.wav
wget    -P amicorpus/IN1007/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1007/audio/IN1007.Mix-Headset.wav
wget    -P amicorpus/IN1008/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1008/audio/IN1008.Mix-Headset.wav
wget    -P amicorpus/IN1009/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1009/audio/IN1009.Mix-Headset.wav
wget    -P amicorpus/IN1012/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1012/audio/IN1012.Mix-Headset.wav
wget    -P amicorpus/IN1013/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1013/audio/IN1013.Mix-Headset.wav
wget    -P amicorpus/IN1014/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1014/audio/IN1014.Mix-Headset.wav
wget    -P amicorpus/IN1016/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1016/audio/IN1016.Mix-Headset.wav
wget https://groups.inf.ed.ac.uk/ami/download/temp/amiBuild-135648-Sat-Sep-7-2024.manifest.txt
wget https://groups.inf.ed.ac.uk/ami/download/temp/../CCBY4.0.txt